#!/usr/bin/env bash

if [ ! -e .git ]; then
    git init
fi

repo="git://git.kernel.org/pub/scm/linux/kernel/git/torvalds/linux.git"
git submodule add "$repo"

repo="git://git.kernel.org/pub/scm/linux/kernel/git/stable/linux-stable.git"
git submodule add -f --reference linux/ "$repo"
